# Generated by Django 5.2.17 on 2026-09-13 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('graduation_year', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
    ]
